re-factored help system

diff --git a/src/bash/common b/src/bash/common
--- a/src/bash/common
+++ b/src/bash/common
@@ -26,22 +26,6 @@ awz_cli_credentials_validated=no
 azure_cli_credentials_validated=no
 google_cli_credentials_validated=no
 
-function usage() {
-  echo -e "${NC}\nUSAGE: vs ${BOLD}<COMMAND>${NORMAL} [options]\n"
-  echo -e "  This CLI manages personal cloud VPN nodes in multiple cloud regions.\n"
-  echo -e "${LIGHT_BLUE}  ${BOLD}<COMMAND>${NORMAL} should be one of the following:\n${GREEN}"
-  echo -e "    ${BOLD}init${NORMAL}                                     Initializes the current folder with the"
-  echo -e "                                             control files which contain the environment"
-  echo -e "                                             for running deployment scripts."
-  echo -e "    ${BOLD}show-regions${NORMAL}         <CLOUD>             Show regions nodes can be created in."
-  echo -e "    ${BOLD}deploy-node${NORMAL}          <VPN_TYPE> <CLOUD>  Deploys or updates a personal VPN node."
-  echo -e "    ${BOLD}reinit-node${NORMAL}          <VPN_TYPE> <CLOUD>  Reinitializes a VPN node's remote state."
-  echo -e "    ${BOLD}destroy-node${NORMAL}         <VPN_TYPE> <CLOUD>  Destroys a VPN node."
-  echo -e "    ${BOLD}download-vpn-config${NORMAL}  <VPN_TYPE> <CLOUD>  Downloads the client VPN configuration."
-  echo -e "    ${BOLD}start-tunnel${NORMAL}                             Starts tunnel services which obfuscate VPN traffic to a node."
-  echo -e "    ${BOLD}show-nodes${NORMAL}                               Show all deployed nodes and their status.${NC}"
-}
-
 function common::set_working_dir() {
 
   working_dir=$(pwd)
@@ -72,20 +56,20 @@ function common::validate_environment() {
     echo -e "${GREEN}to download and install the AWS CLI.${NC}"
     exit 1
   fi
-  which gcloud >/dev/null 2>&1
-  if [[ $? -ne 0 ]]; then
-    echo -e "${RED}\nERROR! Unable to find Google Cloud CLI in the system path.\n" 
-    echo -e "${GREEN}Please follow the instructions at: "
-    echo -e "- ${BLUE}https://cloud.google.com/sdk/docs\n" 
-    echo -e "${GREEN}to download and install the Google Cloud SDK.${NC}"
-    exit 1
-  fi
   which az >/dev/null 2>&1
   if [[ $? -ne 0 ]]; then
     echo -e "${RED}\nERROR! Unable to find Microsoft Azure CLI in the system path.\n" 
     echo -e "${GREEN}Please follow the instructions at: "
     echo -e "- ${BLUE}https://docs.microsoft.com/en-us/cli/azure/install-azure-cli\n" 
     echo -e "${GREEN}to download and install the Microsoft Azure CLI.${NC}"
+    exit 1
+  fi
+  which gcloud >/dev/null 2>&1
+  if [[ $? -ne 0 ]]; then
+    echo -e "${RED}\nERROR! Unable to find Google Cloud CLI in the system path.\n" 
+    echo -e "${GREEN}Please follow the instructions at: "
+    echo -e "- ${BLUE}https://cloud.google.com/sdk/docs\n" 
+    echo -e "${GREEN}to download and install the Google Cloud SDK.${NC}"
     exit 1
   fi
   which terraform >/dev/null 2>&1
@@ -152,14 +136,15 @@ function common::validate_cloud_credentials() {
 
 function common::validate_workspace() {
 
+  local command=$1
   local first
 
-  if [[ ! -e $root_dir/cloud/recipes/$vpn_type ]]; then
-    usage
+  if [[ ! -e ${template_dir}/$vpn_type ]]; then
+    eval "usage::${command}"
     echo -e "${RED}\nERROR! Unknown VPN type.\n" 
     echo -e "${GREEN}Available VPN types for deployment are:\n"
     first=y
-    for d in $(find $root_dir/cloud/recipes -maxdepth 1 -type d -print); do
+    for d in $(find ${template_dir} -maxdepth 1 -type d -print); do
       if [[ $first == n ]]; then
         echo "- \"$(basename $d)\""
       else
@@ -169,12 +154,12 @@ function common::validate_workspace() {
     echo -e "${NC}"
     exit 1
   fi
-  if [[ ! -e $root_dir/cloud/recipes/$vpn_type/$cloud ]]; then
-    usage
+  if [[ ! -e ${template_dir}/$vpn_type/$cloud ]]; then
+    eval "usage::${command}"
     echo -e "${RED}\nERROR! Unknown cloud target for VPN of type \"$vpn_type\".\n" 
     echo -e "${GREEN}Cloud targets available for deployment are:\n"
     first=y
-    for d in $(find $root_dir/cloud/recipes/$vpn_type -maxdepth 1 -type d -print); do 
+    for d in $(find ${template_dir}/$vpn_type -maxdepth 1 -type d -print); do 
       if [[ $first == n ]]; then
         echo "- \"$(basename $d)\""
       else
@@ -260,5 +245,6 @@ function ui::print_nodes_table() {
 }
 
 scripts_dir=$(dirname $BASH_SOURCE)
+source ${scripts_dir}/common_usage
 source ${scripts_dir}/common_cloud
 source ${scripts_dir}/common_terraform
diff --git a/src/bash/download-vpn-config b/src/bash/download-vpn-config
--- a/src/bash/download-vpn-config
+++ b/src/bash/download-vpn-config
@@ -1,21 +1,12 @@
 #!/bin/bash
 
-source $(dirname $BASH_SOURCE)/common
-set -euo pipefail
-
 workspace_dir=$1 && shift
 template_dir=$1 && shift
-vpn_type=$1 && shift
-cloud=$1 && shift
+vpn_type=${1:-<VPN_TYPE>} && shift
+cloud=${1:-<CLOUD>} && shift
 
-function command_usage() {
-  echo -e "\nUSAGE: vs download-vpn-config $vpn_type $cloud [-r|--region <REGION>] [-u|--user <USERNAME>] [-p|--password <PASSWORD>] [-d|--debug]\n"
-  echo -e "${LIGHT_BLUE}  This CLI command downloads the VPN client configuration from the VPN server deployed to the given region.\n${LIGHT_GREEN}"
-  echo -e "  ${BOLD}-r|--region${NORMAL} <REGION>      The region of the server from which the configuration should be downloaded"
-  echo -e "  ${BOLD}-u|--user${NORMAL} <USERNAME>      The name of the VPN user whose client configuration should be downloaded"
-  echo -e "  ${BOLD}-p|--password${NORMAL} <PASSWORD>  The password of the VPN user"
-  echo -e "  ${DIM}-d|--debug${NORMAL}                Enable trace output\n${NC}"
-}
+source $(dirname $BASH_SOURCE)/common
+set -euo pipefail
 
 function download_vpn_config() {
 
@@ -51,10 +42,7 @@ region=""
 user=""
 password=""
 
-if [[ $# -eq 0 ]]; then
-  command_usage
-  exit 1
-fi
+common::validate_workspace download_vpn_config
 while [[ $# -gt 0 ]]; do
   case "$1" in
     -r|--region)
@@ -73,12 +61,12 @@ while [[ $# -gt 0 ]]; do
       set -x
       ;;
     -h|--help)
-      command_usage
+      usage::download_vpn_config
       exit 0
       ;;
     *)
       echo -e "${RED}\nERROR! Unknown option \"$1\".${NC}"
-      command_usage
+      usage::download_vpn_config
       exit 1
       ;;
   esac
@@ -86,18 +74,20 @@ while [[ $# -gt 0 ]]; do
 done
 
 if [[ -z $region ]]; then
+  usage::download_vpn_config
   echo -e "${RED}\nERROR! A region must be specified to identify the"
   echo -e "       VPN server to retrieve the configuration from.${NC}"
+  exit 1
+fi
+if [[ -z "$user" || -z "$password" ]]; then
+  usage::download_vpn_config
+  echo -e "${RED}\nERROR! The user name and password of the VPN user whose"
+  echo -e "       configuration should be download cannot be empty.${NC}"
   exit 1
 fi
 if [[ ! -e ${workspace_dir}/${region} ]]; then
   echo -e "${RED}\nERROR! Deployment workspace path does not exist. The region"
   echo -e "       provided may be invalid or the server may not have been deployed.${NC}"
-  exit 1
-fi
-if [[ -z "$user" || -z "$password" ]]; then
-  echo -e "${RED}\nERROR! The user name and password of the VPN user whose"
-  echo -e "       configuration should be download cannot be empty.${NC}"
   exit 1
 fi
 
diff --git a/src/bash/show-nodes b/src/bash/show-nodes
--- a/src/bash/show-nodes
+++ b/src/bash/show-nodes
@@ -2,11 +2,18 @@
 
 scripts_dir=$(dirname $BASH_SOURCE)
 root_dir=$(cd $scripts_dir/../.. && pwd)
+
 source ${scripts_dir}/common
 set -euo pipefail
 
 workspace_dir=$1 && shift
 template_dir=$1 && shift
+
+if [[ $# -gt 0 ]]; then
+  usage::main
+  echo -e "${RED}\nERROR! \"show-nodes\" command does accept any additional arguments.${NC}"
+  exit 1
+fi
 
 echo -e "\n${GREEN}${BOLD}VPN Nodes deployed to the cloud${NORMAL}"
 echo -e "===============================${NC}\n"
@@ -18,10 +25,15 @@ if [[ ${#vpn_nodes[@]} -eq 0 ]]; then
 fi
 ui::print_nodes_table "${vpn_nodes[@]}"
 
+re='^[0-9]+$'
+
 printf "\n${GREEN}Select node to perform an action on or (q)uit: ${NC}" && read option
 [[ -n $option && $option != q && $option != Q ]] || exit 0
 
-if [[ $option -lt 0 || $option -gt $((${#vpn_nodes[@]}-1)) ]]; then
+if [[ ! $option =~ $re \
+  || $option -lt 0 \
+  || $option -gt $((${#vpn_nodes[@]}-1)) ]]; then
+
   echo -e "${RED}\nERROR! Invalid node selected.${NC}"
   exit 1
 fi
@@ -50,15 +62,13 @@ echo -e "4) Delete Node"
 
 printf "\nSelect action or (q)uit: ${NC}" && read option
 [[ -n $option && $option != q && $option != Q ]] || exit 0
-
-if [[ $option -lt 1 || $option -gt 4 ]]; then
+if [[ ! $option =~ $re || $option -lt 1 || $option -gt 4 ]]; then
   echo -e "${RED}\nERROR! Invalid action selected.${NC}"
   exit 1
 fi
 
 case $option in
   1)
-    common::validate_workspace
     echo
     $scripts_dir/deploy-node \
       $workspace_dir $template_dir \
@@ -66,7 +76,6 @@ case $option in
     ;;
   2)
     if [[ $node_status == running ]]; then
-      common::validate_workspace
       echo -e -n "\n${GREEN}Please enter the VPN username: ${NC}" && read username
       echo -e -n "${GREEN}Please enter the VPN password: ${NC}" && read -s password
 
@@ -90,7 +99,6 @@ case $option in
     esac
     ;;
   4)
-    common::validate_workspace
     echo
     $scripts_dir/destroy-node \
       $workspace_dir $template_dir \
diff --git a/src/bash/start-tunnel b/src/bash/start-tunnel
--- a/src/bash/start-tunnel
+++ b/src/bash/start-tunnel
@@ -1,29 +1,20 @@
 #!/bin/bash
 
-source $(dirname $BASH_SOURCE)/common
-set -euo pipefail
-
 workspace_dir=$1 && shift
 template_dir=$1 && shift
-vpn_type=$1 && shift
-cloud=$1 && shift
+cloud=${1:-<CLOUD>} && shift
 
-function command_usage() {
-  echo -e "${NC}\nUSAGE: vs start-tunnel $vpn_type $cloud [-r|--region <REGION>] [-t|--type <TUNNEL TYPE>] [-d|--debug]\n${LIGHT_BLUE}"
-  echo -e "${LIGHT_BLUE}  This CLI command starts tunnel services which obfuscate VPN traffic to a node.\n${LIGHT_GREEN}"
-  echo -e "  ${BOLD}-r|--region${NORMAL} <REGION>       The region where the node is deployed"
-  echo -e "  ${BOLD}-t|--type${NORMAL} <TUNNEL TYPE>    The type of tunnel. This should be one of:\n"
-  echo -e "                             - udp_over_tcp"
-  echo -e "                             - udp_over_icmp"
-  echo -e "                             - udp_over_udp"
-  echo -e "                             - udp_over_udp_with_fec"
-  echo -e "                             - tcp_over_udp_with_fec\n"
-  echo -e "  ${DIM}-d|--debug${NORMAL}                 Enable trace output${NC}"
-}
+# Obfuscation tunnel service available
+# only for ovpn-x VPN types
+vpn_type=ovpn-x
+
+source $(dirname $BASH_SOURCE)/common
+set -euo pipefail
 
 region=""
 tunnel_type=""
 
+common::validate_workspace start_tunnel
 while [[ $# -gt 0 ]]; do
   case "$1" in
     -r|--region)
@@ -38,12 +29,12 @@ while [[ $# -gt 0 ]]; do
       set -x
       ;;
     -h|--help)
-      command_usage
+      usage::start_tunnel
       exit 0
       ;;
     *)
       echo -e "${RED}\nERROR! Unknown option \"$1\".${NC}"
-      command_usage
+      usage::start_tunnel
       exit 1
       ;;
   esac
@@ -51,8 +42,14 @@ while [[ $# -gt 0 ]]; do
 done
 
 if [[ -z $region ]]; then
+  usage::start_tunnel
   echo -e "${RED}\nERROR! Please provide a cloud region from the following list.${NC}"
   $(dirname $BASH_SOURCE)/show-regions $cloud
+  exit 1
+fi
+if [[ -z $tunnel_type ]]; then
+  usage::start_tunnel
+  echo -e "${RED}\nERROR! Please provide a tunnel type.${NC}"
   exit 1
 fi
 if [[ ! -e ${workspace_dir}/${region}/output.json ]]; then
@@ -63,13 +60,10 @@ fi
 if [[ ! -e ${workspace_dir}/${region}/client_tunnel ]]; then
   echo -e "${RED}\nERROR! The client tunnel script for the node has not been"
   echo -e "       retrieved. You can retrieve it by running the \"download-vpn-config\""
-  echo -e "       command.${NC}"
+  echo -e "       command for this node.${NC}"
   exit 1
 fi
-if [[ -z $tunnel_type ]]; then
-  echo -e "${RED}\nERROR! Please provide a tunnel type.${NC}"
-  exit 1
-fi
+
 if [[ $tunnel_type != udp_over_tcp \
   && $tunnel_type != udp_over_icmp \
   && $tunnel_type != udp_over_udp \
