updated help/messages to show support for non vpn nodes

diff --git a/src/bash/download-vpn-config b/src/bash/download-vpn-config
--- a/src/bash/download-vpn-config
+++ b/src/bash/download-vpn-config
@@ -2,8 +2,13 @@
 
 workspace_dir=$1 && shift
 template_dir=$1 && shift
-vpn_type=${1:-<VPN_TYPE>} && shift
+node_type=${1:-<NODE_TYPE>} && shift
 cloud=${1:-<CLOUD>} && shift
+
+skip_ssl_validation=""
+if [[ -z $TF_VAR_certify_bastion || $TF_VAR_certify_bastion == false ]]; then
+  skip_ssl_validation="-k"
+fi
 
 source $(dirname $BASH_SOURCE)/common
 set -euo pipefail
@@ -16,11 +21,6 @@ function download_vpn_config() {
   local config_file_out=$4
 
   rm -fr $config_file_out
-
-  skip_ssl_validation=""
-  if [[ $TF_VAR_certify_bastion == false ]]; then
-    skip_ssl_validation="-k"
-  fi
 
   set +e
   curl -s -f $skip_ssl_validation \
@@ -91,16 +91,26 @@ if [[ ! -e ${workspace_dir}/${region} ]]; then
   exit 1
 fi
 
-bastion_fqdn=$(cat ${workspace_dir}/${region}/output.json | jq -r .bastion_fqdn.value)
-dns_configured=$(cat ${workspace_dir}/${region}/output.json | jq -r .dns_configured.value)
+output=$(cat ${workspace_dir}/${region}/output.json)
+
+vpn_type=$(echo "$output" | jq -r .vpn_type.value)
+if [[ -z $vpn_type ]]; then
+  echo -e "${RED}\nERROR! Node does not provide a VPN service.${NC}"
+  exit 1
+fi
+
+node_name=$(echo "$output" | jq -r .cb_vpc_name.value)
+vpn_masking_available=$(echo "$output" | jq -r .vpn_masking_available.value)
+bastion_fqdn=$(echo "$output" | jq -r '.cb_managed_instances.value[0] | .fqdn')
+dns_configured=$(echo "$output" | jq -r .dns_configured.value)
 if [[ $dns_configured == true ]]; then
   vpn_server_host=$bastion_fqdn
 else
-  vpn_server_host=$(cat ${workspace_dir}/${region}/output.json | jq -r .bastion_public_ip.value)
+  vpn_server_host=$(echo "$output" | jq -r '.cb_managed_instances.value[0] | .public_ip')
 fi
-echo -e "${GREEN}Downloading VPN configs from \"https://${vpn_server_host}/~${user}/\"...${NC}"
+echo -e "${GREEN}\nDownloading VPN configs from \"https://${vpn_server_host}/~${user}/\"...${NC}"
 
-if [[ $vpn_type == ovpn-x ]]; then
+if [[ $vpn_masking_available == yes ]]; then
   # Download tunnel script
   download_vpn_config $user $password \
     https://${vpn_server_host}/~${user}/client_tunnel \
@@ -109,7 +119,7 @@ if [[ $vpn_type == ovpn-x ]]; then
   chmod +x ${workspace_dir}/${region}/client_tunnel
 fi
 
-working_dir=$(cd $workspace_dir/../../../ && pwd)/configs/${bastion_fqdn}
+working_dir=$(cd $workspace_dir/../../../ && pwd)/configs/${node_name}
 mkdir -p $working_dir
 
 os_type="$(uname -s)"
@@ -117,11 +127,14 @@ os_type="$(uname -s)"
 if [[ $os_type == Darwin ]]; then
 
   case $vpn_type in
-    ipsec)
-      file=${TF_VAR_name}-${vpn_type}-${region}-vpn.mobileconfig
+    wireguard)
+      file=${TF_VAR_name}-wg-${region}-vpn.conf
       ;;
-    ovpn|ovpn-x)
-      file=openvpn-config.tunnelblick.zip
+    openvpn)
+      file=${TF_VAR_name}-ovpn-${region}-vpn.ovpn
+      ;;
+    ipsec)
+      file=${TF_VAR_name}-ipsec-${region}-vpn.mobileconfig
       ;;
   esac
 
@@ -130,34 +143,22 @@ if [[ $os_type == Darwin ]]; then
     ${working_dir}/${file}
 
   case $vpn_type in
-    ipsec)
+    ipsec|openvpn)
       open ${working_dir}/${file}
-      ;;
-    ovpn|ovpn-x)
-      rm -fr ${working_dir}/*.tblk
-      unzip -q -o ${working_dir}/${file} -d $working_dir
-      rm ${working_dir}/${file}
-
-      tunnelblick_config=$(ls -l $working_dir | grep ".tblk" | awk '{ print $9 }')
-      open ${working_dir}/${tunnelblick_config}
       ;;
   esac
 
 elif [[ $os_type == Linux ]]; then
 
-    if [[ $vpn_type == ipsec ]]; then
-
-      file=${TF_VAR_name}-${vpn_type}-${region}-vpn.mobileconfig
+  case $vpn_type in
+    wireguard)
+      file=${TF_VAR_name}-wg-${region}-vpn.conf
       download_vpn_config $user $password \
         https://${vpn_server_host}/~${user}/${file} \
-        ${working_dir}/${file}    
+        ${working_dir}/${file}
+      ;;
 
-      file=${user}.p12
-      download_vpn_config $user $password \
-        https://${vpn_server_host}/~${user}/${file} \
-        ${working_dir}/${file} 
-    else
-
+    openvpn)
       file=openvpn-config.tunnelblick.zip
       download_vpn_config $user $password \
         https://${vpn_server_host}/~${user}/${file} \
@@ -167,32 +168,51 @@ elif [[ $os_type == Linux ]]; then
       unzip -q -o ${working_dir}/${file} -d $working_dir
       rm ${working_dir}/${file}
       
-      file=${TF_VAR_name}-${vpn_type}-${region}-vpn.ovpn
+      file=${TF_VAR_name}-${node_type}-${region}-vpn.ovpn
+      download_vpn_config $user $password \
+        https://${vpn_server_host}/~${user}/${file} \
+        ${working_dir}/${file}       
+      ;;
+
+    ipsec)      
+      file=${TF_VAR_name}-${node_type}-${region}-vpn.mobileconfig
       download_vpn_config $user $password \
         https://${vpn_server_host}/~${user}/${file} \
         ${working_dir}/${file}    
-    fi
 
-    echo -e "${GREEN}\nVPN client config files downloaded to folder \"configs/${bastion_fqdn}/\":\n"
-    first=y
-    for d in $(find ${working_dir} -maxdepth 1 -print); do
-      if [[ $first == n ]]; then
-        echo "- \"$(basename $d)\""
-      else
-        first=n
-      fi      
-    done
+      file=${user}.p12
+      download_vpn_config $user $password \
+        https://${vpn_server_host}/~${user}/${file} \
+        ${working_dir}/${file} 
+      ;;
+  esac
 
-    if [[ $vpn_type == ovpn || $vpn_type == ovpn-x ]]; then
+  echo -e "${GREEN}\nVPN client config files downloaded to folder \"configs/${node_name}/\":\n"
+  first=y
+  for d in $(find ${working_dir} -maxdepth 1 -print); do
+    if [[ $first == n ]]; then
+      echo "- \"$(basename $d)\""
+    else
+      first=n
+    fi      
+  done
+
+  case $vpn_type in
+    wireguard)
+      echo -e "\nImport the \"${file}\" tunnel file into your WireGuard client."
+      ;;
+    openvpn)
       echo -e "\nImport it to your OpenVPN or Tunnelblick client and login using the credentials"
       echo -e "below:\n${NC}"
       echo -e "  user: ${user}"
       echo -e "  password: ${password}\n"
-    else
-      echo -e "\nImport the \"*.mobileconfig\" profile if you are on an Apple device. For all"
-      echo -e "other systems you will need to configure your native IPsec client using the"
+      ;;
+    ipsec)
+      echo -e "\nImport the \"${file}\" profile if you are on an Apple device. For"
+      echo -e "all other systems you will need to configure your native client using the"
       echo -e "provided PKCS key for the user."
-    fi
+      ;;
+  esac
 else
     echo -e "${RED}\nERROR: Unable to determine OS type for which the VPN configurations should be"
     echo -e "       downloaded. Please download manually from:\n${NC}"
diff --git a/src/bash/start-tunnel b/src/bash/start-tunnel
--- a/src/bash/start-tunnel
+++ b/src/bash/start-tunnel
@@ -4,10 +4,6 @@ workspace_dir=$1 && shift
 template_dir=$1 && shift
 cloud=${1:-<CLOUD>} && shift
 
-# Obfuscation tunnel service available
-# only for ovpn-x VPN types
-vpn_type=ovpn-x
-
 source $(dirname $BASH_SOURCE)/common
 set -euo pipefail
 
@@ -74,8 +70,14 @@ if [[ $tunnel_type != udp_over_tcp \
   exit 1
 fi
 
+vpn_masking_available=$(cat $deployment_output | jq -r .vpn_masking_available.value)
+if [[ $vpn_masking_available != true ]]; then
+  echo -e "${RED}\nERROR! Node does not provide a VPN with a masking service.${NC}"
+  exit 1
+fi
+
 deployment_output=${workspace_dir}/${region}/output.json
-bastion_instance_id=$(cat $deployment_output | jq -r .bastion_instance_id.value)
+bastion_instance_id=$(cat $deployment_output | jq -r '.cb_managed_instances.value[0] | .id')
 state=$(cloud::get_node_state "$cloud" "$region" "$bastion_instance_id")
 
 if [[ $state == stopped ]]; then
